### PR TITLE
Add Upper Bounds on Package Dependencies 

### PR DESCRIPTION
**Pull request by ccoffrin**
Should fix travis post JuMP v0.21 release.

### CODE REVIEW

**Comment by ccoffrin** [comment]
@tasseff, is it ok if we merge this and tag a patch release so the package does not break with the latest version of JuMP?

**Comment by tasseff** [comment]
@ccoffrin I never released a version 0.2.0 since I had to move development to the internal GitLab. How about we just call this version 0.2.0, which introduces a few (breaking) changes caused by the JuMP update? See 101bb87

**Comment by ccoffrin** [comment]
Oh, I didn't realize v0.2 was not tagged.  We can call this version v0.2 then.

**Comment by ccoffrin** [comment]
In future releases I recomend at least one version that supports multiple upstream package versions when possible (e.g. JuMP v0.20 and v0.21 in this case).  This makes it easier for other packages to update.

**Pull request merged**
