### PR TITLE
Update documentation build script

### PR DESCRIPTION
**Pull request by odow**
@tasseff could you add me as a collaborator so I have permission to push to `lanl-ansi`? That'll let our `push_preview` deploy and we can see if it still errors.

### CODE REVIEW

**Comment by odow** [comment]
The symlink was last updated 4 years ago: https://github.com/lanl-ansi/WaterModels.jl/blob/gh-pages/latest

So I wonder if it's sufficient to just do a force push and update it. The JuMP docs don't have this problem. 

cc @mortenpi have you ever seen: https://github.com/lanl-ansi/WaterModels.jl/runs/16867659695

**Comment by ccoffrin** [comment]
@odow I added the push role.

**Comment by mortenpi** [comment]
> cc @mortenpi have you ever seen: https://github.com/lanl-ansi/WaterModels.jl/runs/16867659695

Nope. And it looks weird.. why would it suddenly start failing. Maybe just re-run the pages build workflow?

**Comment by odow** [comment]
Closing if favor of #158

**Pull request closed without merging**
